services:
  catrix-smbl:
    container_name: catrix-smbl
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./options.json:/app/options.json:Z"
      - "./session:/app/session:Z"
    restart: unless-stopped

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  ollama:
