[project]
name = "catrix-smbl"
version = "0.1.0"
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matrix-nio[e2e]>=0.24.0",
    "ollama>=0.4.7",
    "pydantic>=2.10.6",
    "simplematrixbotlib>=2.12.3",
]
